### ISSUE TITLE
Finetuning with validation does not work (tutorial settings)

### ISSUE THREAD

**Issue by jlause** [lmb-freiburg/Unet-Segmentation#14]
Hey all,

I am currently testing your ImageJ plugin, following the tutorials.

My setup is Ubuntu 16.04, no CUDA/GPU. I used the pre-build caffe package for CPU (caffe_unet_package_16.04_cpu.zip from https://lmb.informatik.uni-freiburg.de/resources/opensource/unet/).

When I try to follow your finetuning tutorial with the following settings:

![image](https://user-images.githubusercontent.com/34481813/52473825-1a21f580-2b97-11e9-964e-6ef02483f485.png)

I get the following caffee-error, that seems to be related to the IoU-measure computed during validation:

![image](https://user-images.githubusercontent.com/34481813/52473941-5fdebe00-2b97-11e9-838c-f8a6f7c6bab4.png)

Full logfile:

[Log_tutorial.txt](https://github.com/lmb-freiburg/Unet-Segmentation/files/2844735/Log_tutorial.txt)

The following tasks work as expected:
-Segmentation
-Detection
-Finetuning without validation (I terminated after a few iterations, but did not get the error described above)

I hope this helps to improve the software. 
If you need more information, let me know!
Best, Jan.

**Comment by ThorstenFalk** [comment]
Dear Jan,

it looks like you have a concurrent caffe installation on your system that is used instead of the caffe binary shipped with the caffe_unet package. To verify this, please try

ssh localhost which caffe

This probably indicates that you appended the caffe_unet path to your path environment instead of prepending it, so that first the system-wide caffe is found and used. Changing the order should solve your problem in this case

**Comment by jlause** [comment]
Dear Thorsten,

thanks for the fast reply.

Unfortunately, `ssh localhost which caffe` returns the path to the expected unet-related binary: `/home/jan/unet/bin/caffe`

I use the following two lines as first lines in my .bashrc to add the caffe command to my path:

```
export PATH=$PATH:/home/jan/unet/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/jan/unet/lib:/home/jan/unet/extlib
```

So from that I'd take that my adding-to-path order seems fine, right? Any other ideas?

**Comment by ThorstenFalk** [comment]
Indeed, the old CPU build seems to lack the IoULayer, very strange. Please use the new package [caffe_unet_package_16.04_cpu.tar.gz](https://lmb.informatik.uni-freiburg.de/resources/opensource/unet/caffe_unet_package_16.04_cpu.tar.gz) instead.

**Comment by jlause** [comment]
Thanks, using the new package solved the problem!

(I'm moving to a GPU very soon, just wanted to get a quick look ;) )
