### ISSUE TITLE
Model/weight check failed

### ISSUE THREAD

**Issue by yinawang28** [lmb-freiburg/Unet-Segmentation#16]
Dear Thorsten, here I still have some issue in running the example.

Using the following setting: 
![image](https://user-images.githubusercontent.com/45947869/52537646-f1783800-2d1d-11e9-8c1e-e42f133245df.png)
Error:
$ /home/daveb/unet-seg/bin/caffe_unet
$ /home/daveb/unet-seg/bin/caffe_unet
$ caffe_unet check_model_and_weights_h5 -model /home/daveb/Downloads/caffemodels/2d_cell_net_v0.modeldef.h5 -weights /home/daveb/Downloads/2d_cell_net_v0.caffemodel.h5 -n_channels 1 -gpu 0
Model/Weight check failed:
See log for further details
U-Net job aborted

Any idea how to solve this? Any other log file saved to track the issue? Thanks.

Installation and OS details:
Build from source (using instructions from readme); local machine; Ubuntu 18.04 LTS, CUDA 9.0 CuDNN 7

**Comment by ThorstenFalk** [comment]
This is indeed very sparse output. Normally the full error stream of the caffe_unet call should be shown after the colon of "Model/Weight check failed:". Can you try to execute exactly the same command in a shell? It should behave identical and hopefully produce a little more output.

**Comment by ThorstenFalk** [comment]
I rewrote the check for caffe_unet and caffe binary, maybe this helps already.
Independent of the reported problem, you definitely have to edit your IJPrefs.txt and replace .unet.caffeBinary=/home/daveb/unet-seg/bin/caffe_unet by .unet.caffeBinary=/home/daveb/unet-seg/bin/caffe otherwise you won't be able to finetune.

**Comment by yinawang28** [comment]
Thanks for the quick reply and pointing out the things I should keep an eye on about finetune. 
Running the same command in shell indeed gave the trackback and indicated where the error occured:
I0211 14:46:37.216090 11284 caffe_unet.cpp:172] Checking model /home/daveb/Downloads/caffemodels/2d_cell_net_v0.modeldef.h5 and weights /home/daveb/Downloads/2d_cell_net_v0.caffemodel.h5
I0211 14:46:37.216384 11284 caffe_unet.cpp:179] Use GPU with device ID 0
I0211 14:46:37.259383 11284 caffe_unet.cpp:183] GPU device name: GeForce RTX 2080
I0211 14:46:37.619424 11284 caffe_unet.cpp:201] Reading unet ID from '/home/daveb/Downloads/caffemodels/2d_cell_net_v0.modeldef.h5'
I0211 14:46:37.619828 11284 caffe_unet.cpp:205]   unet ID (model) = '2d_cell_net_v0'
I0211 14:46:37.620268 11284 caffe_unet.cpp:240] Reading unet ID from '/home/daveb/Downloads/2d_cell_net_v0.caffemodel.h5'
I0211 14:46:37.620470 11284 caffe_unet.cpp:271] '/home/daveb/Downloads/2d_cell_net_v0.caffemodel.h5' does not contain '/.unet_ident'
....(model information omitted)
F0211 14:46:38.635483 11284 cudnn_conv_layer.cu:28] Check failed: status == CUDNN_STATUS_SUCCESS (8 vs. 0)  CUDNN_STATUS_EXECUTION_FAILED
*** Check failure stack trace: ***
    @     0x7ff60dd8c0cd  google::LogMessage::Fail()
    @     0x7ff60dd8df33  google::LogMessage::SendToLog()
    @     0x7ff60dd8bc28  google::LogMessage::Flush()
    @     0x7ff60dd8e999  google::LogMessageFatal::~LogMessageFatal()
    @     0x7ff60e584a9b  caffe::CuDNNConvolutionLayer<>::Forward_gpu()
    @     0x7ff60e4cc431  caffe::Net<>::ForwardFromTo()
    @     0x7ff60e4cc537  caffe::Net<>::Forward()
    @     0x56119bd64785  check_model_and_weights_h5()
    @     0x56119bd60f20  main
    @     0x7ff60c3a9b97  __libc_start_main
    @     0x56119bd6189a  _start
Aborted (core dumped)

I'm using specifically cuDNN 7.1.4. Do you think this is a cuDNN version problem? Previously we have a project which uses tensorflow, and similar weird cuDNN error occurs. We resolved it by changing to cuDNN 7.1.4.

**Comment by yinawang28** [comment]
Here is the output form plugin built from the latest commit:
$ caffe_unet
Setting caffe_unet binary path to caffe_unet
Searching for /home/daveb/unet-seg/bin/caffe_unet
$ /home/daveb/unet-seg/bin/caffe_unet
$ caffe_unet check_model_and_weights_h5 -model /home/daveb/Downloads/caffemodels/2d_cell_net_v0.modeldef.h5 -weights /home/daveb/Downloads/caffemodels/2d_cell_net_v0.caffemodel.h5 -n_channels 1 -gpu 0
Model/Weight check failed:
See log for further details
U-Net job aborted

**Comment by ThorstenFalk** [comment]
Our tarball has been built with cuda 9.2 with associated cuDNN 7.4.1.5, so there might indeed be version issues. Since you need this specific cuda/cuDNN combination for your tensorflow installation, I would suggest to build from scratch. Our build uses the following sequence of commands:

```
apt-get update
apt-get install -y sudo wget unzip openssh-server git build-essential cmake libboost-system-dev libboost-thread-dev libboost-filesystem-dev libprotobuf-dev protobuf-compiler libhdf5-serial-dev libatlas-base-dev libgoogle-glog-dev python3-dev python3-numpy libboost-python-dev
git clone https://github.com/BVLC/caffe.git
cd caffe
git checkout 99bd99795dcdf0b1d3086a8d67ab1782a8a08383
wget https://lmb.informatik.uni-freiburg.de/lmbsoft/unet/caffe_unet_99bd99_20190109.patch
git apply caffe_unet_99bd99_20190109.patch
mkdir x86_64
cd x86_64
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS_RELEASE="-O2 -DNDEBUG" -DCMAKE_C_FLAGS_RELEASE="-O2 -DNDEBUG" -DCPU_ONLY=OFF -DUSE_OPENMP=ON -DCMAKE_INSTALL_PREFIX=/home/daveb/unet-seg -DUSE_OPENCV=OFF -DUSE_LEVELDB=OFF -DUSE_LMDB=OFF -DUSE_NCCL=OFF -DBUILD_python=ON -DBUILD_python_layer=ON -Dpython_version=3 -DCUDA_ARCH_NAME=Manual -DCUDA_ARCH_BIN="30 35 50 60 61 62" -DCUDA_ARCH_PTX="30" -DUSE_CUDNN=ON ..
make -j install
```

**Comment by ThorstenFalk** [comment]
You still have to manually replace `.unet.caffeBinary=/home/daveb/unet-seg/bin/caffe_unet` by `.unet.caffeBinary=/home/daveb/unet-seg/bin/caffe` to make finetuning work.

**Comment by yinawang28** [comment]
Indeed caffe_unet is already build from source in my machine. 
Also I have already replaced caffeBinary in IJ_Prefs.txt in testing the version from the latest commit. Do you see anything particularly wrong in the log?

**Comment by ThorstenFalk** [comment]
> Here is the output form plugin built from the latest commit:
> $ caffe_unet
> Setting caffe_unet binary path to caffe_unet
> Searching for /home/daveb/unet-seg/bin/caffe_unet
> $ /home/daveb/unet-seg/bin/caffe_unet

the "Searching for ..." line should read "Searching for /home/daveb/unet-seg/bin/caffe" or just "caffe". At best remove both lines `.unet.caffeBinary=xxx` and `.unet.caffe_unetBinary=xxx` from your IJPrefs.txt

Regarding the real problem: If you already built from scratch I am running out of explanations for the cuDNN error. I experienced strange cuDNN errors when approaching the memory limit of the GPU because workspaces could not be allocated, but that's obviously not the case with the tiny tiles you use, except, if you share the GPU and it was already almost fully occupied, but that would be coincidence and not reproducible.

you could try `ldd $(which caffe_unet)` to find out which libraries are actually used during execution and compare this to the set of libraries used during build, if they are identical, I am out of ideas for the moment.

**Comment by yinawang28** [comment]
This is the output of checking what libraries are used:
	linux-vdso.so.1 (0x00007ffe462da000)
	libcaffe.so.1.0.0 => /home/daveb/unet-seg/lib/libcaffe.so.1.0.0 (0x00007f4e8222a000)
	libboost_system.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.65.1 (0x00007f4e82025000)
	libglog.so.0 => /usr/lib/x86_64-linux-gnu/libglog.so.0 (0x00007f4e81df4000)
	libgflags.so.2.2 => /usr/lib/x86_64-linux-gnu/libgflags.so.2.2 (0x00007f4e81bcf000)
	libhdf5_serial.so.100 => /usr/lib/x86_64-linux-gnu/libhdf5_serial.so.100 (0x00007f4e81677000)
	libhdf5_serial_hl.so.100 => /usr/lib/x86_64-linux-gnu/libhdf5_serial_hl.so.100 (0x00007f4e81454000)
	libprotobuf.so.10 => /usr/lib/x86_64-linux-gnu/libprotobuf.so.10 (0x00007f4e80ffb000)
	libcudart.so.9.0 => /usr/local/cuda/lib64/libcudart.so.9.0 (0x00007f4e80d8e000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4e80a05000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4e807ed000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4e803fc000)
	libboost_thread.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.65.1 (0x00007f4e801d7000)
	libboost_filesystem.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1 (0x00007f4e7ffbd000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4e7fd9e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4e7fa00000)
	libcurand.so.9.0 => /usr/local/cuda/lib64/libcurand.so.9.0 (0x00007f4e7ba9c000)
	libcublas.so.9.0 => /usr/local/cuda/lib64/libcublas.so.9.0 (0x00007f4e78666000)
	libcudnn.so.7 => /usr/local/cuda/lib64/libcudnn.so.7 (0x00007f4e64675000)
	libcblas.so.3 => /usr/lib/x86_64-linux-gnu/libcblas.so.3 (0x00007f4e64453000)
	libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007f4e64238000)
	libsz.so.2 => /usr/lib/x86_64-linux-gnu/libsz.so.2 (0x00007f4e64035000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f4e63e18000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4e63c14000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4e833b8000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f4e63a0c000)
	libatlas.so.3 => /usr/lib/x86_64-linux-gnu/libatlas.so.3 (0x00007f4e63483000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f4e6325d000)
	libaec.so.0 => /usr/lib/x86_64-linux-gnu/libaec.so.0 (0x00007f4e63055000)

which matched my local machine libraries. I noticed you have the built version without cuDNN. I tried to set USE_CUDNN to OFF in caffe's cmake file, but it seems to result in cmake configuration error.
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/daveb/unet-seg -DUSE_OPENCV=OFF -DUSE_LEVELDB=OFF -DUSE_LMDB=OFF -DBUILD_python=OFF -DBUILD_python_layer=OFF -DCUDA_ARCH_NAME=Manual -DCUDA_ARCH_BIN="50 52 60 61 70" -DCUDA_ARCH_PTX="70" ..
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
--   chrono
--   date_time
--   atomic
-- Found GFlags: /usr/include  
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found Glog: /usr/include  
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.0.0") 
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_cpp.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.0.1") found components:  HL 
-- CUDA detected: 9.0
-- Added CUDA NVCC flags for: sm_50 sm_52 sm_60 sm_61 sm_70 compute_70
-- Found Atlas: /usr/include/x86_64-linux-gnu  
-- Found Atlas (include: /usr/include/x86_64-linux-gnu library: /usr/lib/x86_64-linux-gnu/libatlas.so lapack: /usr/lib/x86_64-linux-gnu/liblapack.so
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
CMake Error at CMakeLists.txt:88 (list):
  list sub-command REMOVE_ITEM requires list to be present.


CMake Error at src/caffe/CMakeLists.txt:30 (target_compile_definitions):
  target_compile_definitions called with incorrect number of arguments


-- Python interface is disabled or not all required dependencies found. Building without it...
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- 
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0
--   Git               :   1.0-132-g99bd9979-dirty
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   OFF
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   OFF
--   USE_LEVELDB       :   OFF
--   USE_LMDB          :   OFF
--   USE_NCCL          :   OFF
--   ALLOW_LMDB_NOLOCK :   OFF
--   USE_HDF5          :   ON
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.65)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 3.0.0)
--   CUDA              :   Yes (ver. 9.0)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Manual
--   GPU arch(s)       :   sm_50 sm_52 sm_60 sm_61 sm_70 compute_70
--   cuDNN             :   Disabled
-- 
-- Documentaion:
--   Doxygen           :   No
--   config_file       :   
-- 
-- Install:
--   Install path      :   /home/daveb/unet-seg
-- 
-- Configuring incomplete, errors occurred!
See also "/home/daveb/caffe/x86_64/CMakeFiles/CMakeOutput.log".
See also "/home/daveb/caffe/x86_64/CMakeFiles/CMakeError.log".

**Comment by ThorstenFalk** [comment]
Grmpf, the CMakeLists.txt is 100% BVLC original, so there seems to be a problem with caffe itself. I cannot test it right now, because I cannot freshly clone caffe (Internal Server error on github), but will try later.

**Comment by ThorstenFalk** [comment]
github still does not allow me to clone BVLC/caffe.git :(. Did you try with a fresh and empty build directory?

**Comment by yinawang28** [comment]
Yes, every build was done by delete and make a new x86_64 folder. Did you build your none-cuDNN version the same way?

**Comment by ThorstenFalk** [comment]
I usually enable python, but this should not really make a difference. The error occurs, when PUBLIC and PRIVATE flags are purged from the command line for nvcc. It looks like the DEFINITIONS are empty in this case, so that the replace command only sees two of the three required parameters.

**Comment by ThorstenFalk** [comment]
I just tried in a virtual environment with your setup and configuration went through without errors.
Last bet: What is your cmake version?

**Comment by yinawang28** [comment]
CMake version 3.10.2
Yes, initially I was using gcc 7, but got make error of not supporting gcc later than 6. So tried gcc 6.5 and 5.5, both no luck. 
Anyway, thanks a lot for the help!

**Comment by ThorstenFalk** [comment]
Not even dockerhub nvidia/cuda has an image for Ubuntu 18.04 and cuda 9.0, maybe you should upgrade to at least cuda 9.2 or better 10 with corresponding cuDNN 7, for both combinations I have ready binaries. But check with the developers of CSBDeep, whether they support any of those combinations, too, if you want to use CSBDeep on the same machine.

**Comment by yinawang28** [comment]
Hi Thorsten, thanks for the always so prompt reply! I think docker is a great idea. Looking forward to your repo.

**Comment by ThorstenFalk** [comment]
Voilà: [caffe-unet-docker](https://github.com/lmb-freiburg/caffe-unet-docker)

**Comment by ThorstenFalk** [comment]
Does it run in docker?

**Comment by HyacintViolet** [comment]
Hi Thorsten, I just had the same issue.
![modelweight_check_failed](https://user-images.githubusercontent.com/12589928/97880829-96417100-1d5c-11eb-975d-a7ac3d220aa4.png)
I'm using Ubuntu 18.04 LTS, CUDA 10.0 CuDNN 7.6.5.32

Do you think there's a solution? or should I try docker?

**Comment by HyacintViolet** [comment]
Update:
It turns out after CUDA&CuDNN installation, the system has not been rebooted, so the Nvidia driver was not properly configured. This is verified by running `nvidia-smi` and seeing:
`NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.`

Rebooting the system solved the problem.
