### ISSUE TITLE
Finetuning can't find 'train', aborts

### ISSUE THREAD

**Issue by jlause** [lmb-freiburg/Unet-Segmentation#19]
Dear all,

I moved to GPU for finetuning, using the following setup:

Server: CUDA 10.0, cuDNN 7, Ubuntu 18, running within a docker container into which I ssh
Client: Ubuntu 16

I use the binaries provided at https://lmb.informatik.uni-freiburg.de/resources/opensource/unet/caffe_unet_package_18.04_gpu_cuda10_cudnn7.tar.gz

Segmentation and Detection work fine with this setup. However, finetuning does not even start, aborting with the following error:
![image](https://user-images.githubusercontent.com/34481813/52724898-7bd7ca80-2fb0-11e9-92b7-13bebb7e082c.png)
The log output:
![image](https://user-images.githubusercontent.com/34481813/52724862-6c588180-2fb0-11e9-8ab6-7bee81273c05.png)
I use the following settings:
![image](https://user-images.githubusercontent.com/34481813/52724993-a75ab500-2fb0-11e9-97b0-cceacb63cdc8.png)

Thanks in advance for any hint what I might be doing wrong. If you need more details to reproduce, let me know!
Cheers, Jan.

**Comment by ThorstenFalk** [comment]
Interesting, this is a bug in the caffe binary check, I did not expect that the empty string as command would pass... I'll fix it asap

**Comment by ThorstenFalk** [comment]
Please try the latest version. It should reset your caffeBinary path to "caffe" and will present the dialog for entering the full path if caffe is not in your PATH envrionent.

**Comment by jlause** [comment]
Ok, thanks a lot for the fast reply and fix! 

Sorry for the naive question: Do I have to build from source then or will you also update the pre-build binaries on https://lmb.informatik.uni-freiburg.de/resources/opensource/unet/ ?

**Comment by ThorstenFalk** [comment]
The bug is only plugin-related, simply get the latest version using Help->Update.

**Comment by jlause** [comment]
great, fixed it for me, thanks for the fast support!
