### ISSUE TITLE
Macro call does not properly respect Windows paths

### ISSUE THREAD

**Issue by ThorstenFalk** [lmb-freiburg/Unet-Segmentation#2]
call('de.unifreiburg.unet.SegmentationJob.processHyperStack', 'modelFilename=C:\Users\username\Desktop\xxx\xxx.modeldef.h5,weightsFilename=xxx.caffemodel.h5,Tile shape (px):=724x516,gpuId=GPU 0,useRemoteHost=true,hostname=lmbunet.informatik.uni-freiburg.de,port=2222,username=unetuser,processFolder=,average=none,keepOriginal=true,outputScores=false,outputSoftmaxScores=false');

failed with log output

>    (Fiji Is Just) ImageJ 2.0.0-rc-68/1.52i; Java 1.8.0_66 [64-bit]; Windows 10 10.0; 1083MB of 6024MB (17%)
>  
>    java.lang.reflect.InvocationTargetException
> 
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 
> 	at ij.macro.Functions.call(Functions.java:4379)
> 
> 	at ij.macro.Functions.getStringFunction(Functions.java:274)
> 
> 	at ij.macro.Interpreter.getStringTerm(Interpreter.java:1366)
> 
> 	at ij.macro.Interpreter.getString(Interpreter.java:1344)
> 
> 	at ij.macro.Interpreter.doStatement(Interpreter.java:304)
> 
> 	at ij.macro.Interpreter.doStatements(Interpreter.java:236)
> 
> 	at ij.macro.Interpreter.run(Interpreter.java:119)
> 
> 	at ij.macro.Interpreter.run(Interpreter.java:90)
> 
> 	at ij.macro.Interpreter.run(Interpreter.java:101)
> 
> 	at ij.plugin.Macro_Runner.runMacro(Macro_Runner.java:161)
> 
> 	at ij.IJ.runMacro(IJ.java:147)
> 
> 	at ij.IJ.runMacro(IJ.java:136)
> 
> 	at net.imagej.legacy.IJ1Helper$3.call(IJ1Helper.java:1098)
> 
> 	at net.imagej.legacy.IJ1Helper$3.call(IJ1Helper.java:1094)
> 
> 	at net.imagej.legacy.IJ1Helper.runMacroFriendly(IJ1Helper.java:1045)
> 
> 	at net.imagej.legacy.IJ1Helper.runMacro(IJ1Helper.java:1094)
> 
> 	at net.imagej.legacy.plugin.IJ1MacroEngine.eval(IJ1MacroEngine.java:137)
> 
> 	at org.scijava.script.ScriptModule.run(ScriptModule.java:160)
> 
> 	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
> 
> 	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
> 
> 	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
> 
> 	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
> 
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 
> 	at java.lang.Thread.run(Thread.java:745)
> 
>    Caused by: ncsa.hdf.hdf5lib.exceptions.HDF5FileNotFoundException: Path does not exit. 
>    (C:\Fiji\UsersusernameDesktop xxx	xx.modeldef.h5)
> 
> 	at ch.systemsx.cisd.hdf5.HDF5BaseReader.openFile(HDF5BaseReader.java:194)
> 
> 	at ch.systemsx.cisd.hdf5.HDF5BaseReader.<init>(HDF5BaseReader.java:147)
> 
> 	at ch.systemsx.cisd.hdf5.HDF5BaseReader.<init>(HDF5BaseReader.java:126)
> 
> 	at ch.systemsx.cisd.hdf5.HDF5ReaderConfigurator.reader(HDF5ReaderConfigurator.java:86)
> 
> 	at de.unifreiburg.unet.ModelDefinition._load(ModelDefinition.java:304)
> 
> 	at de.unifreiburg.unet.ModelDefinition.load(ModelDefinition.java:809)
> 
> 	at de.unifreiburg.unet.SegmentationJob.processHyperStack(SegmentationJob.java:604)
> 
> 	... 30 more
>

**Comment by ThorstenFalk** [comment]
Confirmed

**Comment by ThorstenFalk** [comment]
nio.File toString() should produce escaped backslash characters so that instead of c:\xyc\abc c:\\xyz\\abc is saved when recording macros. That will probably work, but is not very nice if the user wants to write the macro himself or change the path programmatically.

**Comment by ThorstenFalk** [comment]
In all paths written to the Macro Recorder \ characters have been replaced by / characters to make the calls platform independent. This should hopefully solve this issue.

**Comment by JahnJ** [comment]
> In all paths written to the Macro Recorder \ characters have been replaced by / characters to make the calls platform independent. This should hopefully solve this issue.

The path for the RSAKeyfile is still written with "\" to the macro recorder. Tested with latest version (20190719) on Windows.

**Comment by ThorstenFalk** [comment]
Agreed, should be fixed! Thanks.
