### ISSUE TITLE
What to put WeightsFilename in "de.unifreiburg.unet.DetectionJob.processHyperStack" ?

### ISSUE THREAD

**Issue by hanginzer** [lmb-freiburg/Unet-Segmentation#22]
In the tutorial video, it seems a caffemodel is specified in WeightsFilename for detection, however, when I specify a caffemodel in WeightsFilename with "de.unifreiburg.unet.DetectionJob.processHyperStack" it does not work. But, using ".modeldef.h5", it is fine.

Is there any problems if I put ".modeldef.h5" in WeightsFilename with "de.unifreiburg.unet.DetectionJob.processHyperStack"?

Thank you.

**Comment by ThorstenFalk** [comment]
I assume that the `caffe_unet check_model_and_weights_h5` call failed? Can you please provide the corresponding lines from the log (or the full log output)? Which model did you use?

The .modeldef.h5 file does not contain weights, it only defines the architecture. If you pass in the .modeldef.h5 file as WeightsFilename, the plugin will initialize network weights randomly, leading to structured noise as detection result.

**Comment by hanginzer** [comment]
Thank you very much for your repose.

I am so sorry but now it works even though I failed that process multiple times when I posed this.
If this problem happens again, I will post it again.
