### ISSUE TITLE
Model output is empty

### ISSUE THREAD

**Issue by Zoobidou** [lmb-freiburg/Unet-Segmentation#25]
Hi,

I am new with U-net and not so good with linux. We asked our university IT guys to set up a U-net server in our Lab and they installed Ubunutu 18.04, with CUDA 10 and cuDNN 7.

I downloaded the caffemodels and the sample data from your website: https://lmb.informatik.uni-freiburg.de/lmbsoft/unet/#installation-backend-fromsource

I followed the tutorial video for segmentation and added our U-net server (I'm using Fiji on a Windows 10 laptop) and all the corresponding caffemodel and weights. The plugin seems to communicate well with the server but the model output an empty normalized image (all pixels are Zeros) and an empty segmentation image. I used the BF-microspores image for that.

Here is what the log window in Fiji shows:

`Establishing SSH connection for 'uppersat@uppersatpc1:22'
$ sftp "C:\Users\tala\AppData\Local\Temp\unet-1d2151f8-4485-433f-8ad0-87d8d0ebdc766776308919625221650.tmp" "uppersat@uppersatpc1:22:/home/uppersat/caffemodels/unet-1d2151f8-4485-433f-8ad0-87d8d0ebdc766776308919625221650.tmp"
uppersat@uppersatpc1 $ rm "/home/uppersat/caffemodels/unet-1d2151f8-4485-433f-8ad0-87d8d0ebdc766776308919625221650.tmp"
uppersat@uppersatpc1$ /data/u-net/bin/caffe
uppersat@uppersatpc1$ /data/u-net/bin/caffe_unet
$ sftp "C:\Users\tala\Downloads\2d_cell_net_v0_model\2d_cell_net_v0.modeldef.h5" "uppersat@uppersatpc1:22:/home/uppersat/caffemodels/unet-1d2151f8-4485-433f-8ad0-87d8d0ebdc76.modeldef.h5"
uppersat@uppersatpc1$ caffe_unet check_model_and_weights_h5 -model "caffemodels/unet-1d2151f8-4485-433f-8ad0-87d8d0ebdc76.modeldef.h5" -weights "2d_cell_net_v0.caffemodel.h5" -n_channels 1 -gpu 0
Rescaling Hyperstack (xy) from (0.5319140448180135, 0.5319140448180135) to (0.5, 0.5)
t = 1: scale = Infinity, offset = -0.0
Caffe blobs saved to 'C:\Users\tala\AppData\Local\Temp\unet-1d2151f8-4485-433f-8ad0-87d8d0ebdc768842665550246266494.h5'
$ sftp "C:\Users\tala\AppData\Local\Temp\unet-1d2151f8-4485-433f-8ad0-87d8d0ebdc768842665550246266494.h5" "uppersat@uppersatpc1:22:/home/uppersat/caffemodels/unet-1d2151f8-4485-433f-8ad0-87d8d0ebdc76.h5"
caffe_unet tiled_predict -infileH5 caffemodels/unet-1d2151f8-4485-433f-8ad0-87d8d0ebdc76.h5 -outfileH5 caffemodels/unet-1d2151f8-4485-433f-8ad0-87d8d0ebdc76.h5 -model caffemodels/unet-1d2151f8-4485-433f-8ad0-87d8d0ebdc76.modeldef.h5 -weights 2d_cell_net_v0.caffemodel.h5 -iterations 0 -gpu_mem_available_MB 8000 -gpu 0 
$ sftp "uppersat@uppersatpc1:22:/home/uppersat/caffemodels/unet-1d2151f8-4485-433f-8ad0-87d8d0ebdc76.h5" "C:\Users\tala\AppData\Local\Temp\unet-1d2151f8-4485-433f-8ad0-87d8d0ebdc768842665550246266494.h5"
uppersat@uppersatpc1 $ rm "/home/uppersat/caffemodels/unet-1d2151f8-4485-433f-8ad0-87d8d0ebdc76.modeldef.h5"
uppersat@uppersatpc1 $ rm "/home/uppersat/caffemodels/unet-1d2151f8-4485-433f-8ad0-87d8d0ebdc76.h5"
Removing C:\Users\tala\AppData\Local\Temp\unet-1d2151f8-4485-433f-8ad0-87d8d0ebdc768842665550246266494.h5
U-Net job finished
`

I don't see any errors and would like to know what might be the cause for a blank output.

Also If a try finetunning the model with the erytrocytes images my training curves are weird compared to the tutorial video:

![image](https://user-images.githubusercontent.com/34740200/53427617-90bd5080-39e9-11e9-8f1f-f452d6df817d.png)

And if I try to use the retrained model I get and empty output again.

**Comment by ThorstenFalk** [comment]
According to the log, already the input image was empty... `scale = Infinity, offset = -0.0`. Also the scales are wrong `Rescaling Hyperstack (xy) from (0.5319140448180135, 0.5319140448180135) to (0.5, 0.5)`. Are you sure you selected the microspore image before starting the segmentation job?

**Comment by Zoobidou** [comment]
Yes, if I don't have it open the plugin tells me there are no images open  and doesn't run. Maybe I pasted the log window of another test I did with another image.

Here is the log window with the microspore image (the scale is also to infinity and offset=-0.0):

Could there be an issue in downloading the image to the server?

`Establishing SSH connection for 'uppersat@uppersatpc1:22'
$ sftp "C:\Users\tala\AppData\Local\Temp\unet-97b31caf-7402-4f6a-872f-57e6b504f3389177248322648955395.tmp" "uppersat@uppersatpc1:22:/home/uppersat/caffemodels/unet-97b31caf-7402-4f6a-872f-57e6b504f3389177248322648955395.tmp"
uppersat@uppersatpc1 $ rm "/home/uppersat/caffemodels/unet-97b31caf-7402-4f6a-872f-57e6b504f3389177248322648955395.tmp"
uppersat@uppersatpc1$ /data/u-net/bin/caffe
uppersat@uppersatpc1$ /data/u-net/bin/caffe_unet
$ sftp "C:\Users\tala\Downloads\caffemodels\caffemodels\2d_cell_net_v0.modeldef.h5" "uppersat@uppersatpc1:22:/home/uppersat/caffemodels/unet-97b31caf-7402-4f6a-872f-57e6b504f338.modeldef.h5"
uppersat@uppersatpc1$ caffe_unet check_model_and_weights_h5 -model "caffemodels/unet-97b31caf-7402-4f6a-872f-57e6b504f338.modeldef.h5" -weights "2d_cell_net_v0.caffemodel.h5" -n_channels 1 -gpu 0
Rescaling Hyperstack (xy) from (0.26595702240900676, 0.26595702240900676) to (0.5, 0.5)
t = 1: scale = Infinity, offset = -0.0
Caffe blobs saved to 'C:\Users\tala\AppData\Local\Temp\unet-97b31caf-7402-4f6a-872f-57e6b504f3387556079255735647151.h5'
$ sftp "C:\Users\tala\AppData\Local\Temp\unet-97b31caf-7402-4f6a-872f-57e6b504f3387556079255735647151.h5" "uppersat@uppersatpc1:22:/home/uppersat/caffemodels/unet-97b31caf-7402-4f6a-872f-57e6b504f338.h5"
caffe_unet tiled_predict -infileH5 caffemodels/unet-97b31caf-7402-4f6a-872f-57e6b504f338.h5 -outfileH5 caffemodels/unet-97b31caf-7402-4f6a-872f-57e6b504f338.h5 -model caffemodels/unet-97b31caf-7402-4f6a-872f-57e6b504f338.modeldef.h5 -weights 2d_cell_net_v0.caffemodel.h5 -iterations 0 -gpu_mem_available_MB 4000 -gpu 0 
$ sftp "uppersat@uppersatpc1:22:/home/uppersat/caffemodels/unet-97b31caf-7402-4f6a-872f-57e6b504f338.h5" "C:\Users\tala\AppData\Local\Temp\unet-97b31caf-7402-4f6a-872f-57e6b504f3387556079255735647151.h5"
uppersat@uppersatpc1 $ rm "/home/uppersat/caffemodels/unet-97b31caf-7402-4f6a-872f-57e6b504f338.modeldef.h5"
uppersat@uppersatpc1 $ rm "/home/uppersat/caffemodels/unet-97b31caf-7402-4f6a-872f-57e6b504f338.h5"
Removing C:\Users\tala\AppData\Local\Temp\unet-97b31caf-7402-4f6a-872f-57e6b504f3387556079255735647151.h5
U-Net job finished
`

**Comment by ThorstenFalk** [comment]
Normalization happens on the client before upload, so it is definitely not server-related. Element size is correct now, but `scale = Infinity` indicates division by zero in `scale = 1 / (max(image) - min(image))`. Since `offset = -min(image) = -0.0` the selected hyperstack had intensities from 0 to 0, which is very strange. Which version of Fiji are you using?

**Comment by Zoobidou** [comment]
I'm using Fiji with ImageJ 1.51n

**Comment by ThorstenFalk** [comment]
Recent enough to work, I'd say. I will try to reproduce it on my Windows machine, but never experienced problems during normalization, up to now.

**Comment by Zoobidou** [comment]
OK I downloaded a new fiji version and it works just fine!
I don't know why it was not working with my previous fiji. But Anyway thanks for the help!

**Comment by Zoobidou** [comment]
it's the version 1.52i

**Comment by ThorstenFalk** [comment]
OK, great, although I wonder what was wrong with the old version... well better don't ask
