### ISSUE TITLE
Train and Test 3D images in ImageJ(Fiji) using U-Net Plugin

### ISSUE THREAD

**Issue by jihoon2040** [lmb-freiburg/Unet-Segmentation#28]
Dear all,

Hi, I am Jihoon and learning about U-Net nowadays.
I want to train and test 3D image data using 3D U-Net Plugin in ImageJ(Fiji).
Is it possible to do it?
Also, if anybody knows how to do it, can you write the procedure? 
Thank you.

**Comment by ThorstenFalk** [comment]
Hi Jihoon,
Yes, 3D training and segmentation/detection is possible. Please refer to Supplementary Note 2 (Annotation Guide) of our [U-Net Paper](https://www.nature.com/articles/s41592-018-0261-2) on how to prepare your data for training. You can also obtain a pre-print from the [lmb publications site](https://lmb.informatik.uni-freiburg.de/Publications/2019/FMBCAMBBR19/).
All the best,
Thorsten
