### ISSUE TITLE
Question:  How to generate weight file when training from scratch?

### ISSUE THREAD

**Issue by jlause** [lmb-freiburg/Unet-Segmentation#30]
Hey all,

I want to train the model architecture you provide as pre-trained "base model" from scratch. Thus, I used the plugin function under `U-Net/Utilities/Create new model ` which created a new modeldef.h5 file, but no randomly initialized weight file as far as I can see.

What is the way to go here? How can I start a training without a weight file? Or does the plugin offer a way to generate the initial weights so I can use the finetuning functions to train from scratch? Or do I have to interface with the command line tools somehow?

Happy for any hint, thanks in advance!

Jan.

**Comment by ThorstenFalk** [comment]
Weights that are not available when starting a training/finetuning will be randomly initialized using the MSRA filler (Gaussian scaled with number of input channels) of caffe. So if you do not need a specific initialization, just train without providing a weight file.

**Comment by jlause** [comment]
Ah, much easier than I though. Thanks!
