### ISSUE TITLE
Input/Output error: java.io.IOException: Error during segmentation:exit status -1

### ISSUE THREAD

**Issue by Wenliangwang** [lmb-freiburg/Unet-Segmentation#33]
Amozon EC2 Ubuntu Server 16.04 LTS (HVM)
CPU 
tile shape 500x500

Input/Output error: java.io.IOException: Error during segmentation:exit status -1
unknown caffe error

Log before error:
I0420 13:50:03.208966  7217 net.cpp:814] Ignoring source layer def_data-data2
I0420 13:50:03.209018  7217 net.cpp:814] Ignoring source layer def_label-crop
I0420 13:50:03.209081  7217 net.cpp:814] Ignoring source layer def_weight-crop
I0420 13:50:03.209127  7217 net.cpp:814] Ignoring source layer dropout_d3c
I0420 13:50:03.209172  7217 net.cpp:814] Ignoring source layer dropout_d4c
I0420 13:50:03.209226  7217 net.cpp:814] Ignoring source layer loaddata
I0420 13:50:03.209272  7217 net.cpp:814] Ignoring source layer loss
I0420 13:50:03.209573  7217 net.cpp:814] Ignoring source layer reshape_data
I0420 13:50:03.209621  7217 net.cpp:814] Ignoring source layer reshape_labels
I0420 13:50:03.209668  7217 net.cpp:814] Ignoring source layer reshape_weights
I0420 13:50:03.209715  7217 net.cpp:814] Ignoring source layer reshape_weights2
I0420 13:50:03.214604  7217 tiled_predict.cpp:656] ----> tile (0,0)
F0420 13:50:03.564906  7217 syncedmem.hpp:33] Check failed: *ptr host allocation of size 1065369600 failed
*** Check failure stack trace: ***
    @     0x7f6e343885cd  google::LogMessage::Fail()
    @     0x7f6e3438a433  google::LogMessage::SendToLog()
    @     0x7f6e3438815b  google::LogMessage::Flush()
    @     0x7f6e3438ae1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f6e34adb183  caffe::SyncedMemory::mutable_cpu_data()
    @     0x7f6e34ab5982  caffe::Blob<>::mutable_cpu_data()
    @     0x7f6e348eb298  caffe::BaseConvolutionLayer<>::forward_cpu_gemm()
    @     0x7f6e3491fc46  caffe::ConvolutionLayer<>::Forward_cpu()
    @     0x7f6e34ae5d53  caffe::Net<>::ForwardFromTo()
    @     0x7f6e34ae5f56  caffe::Net<>::Forward()
    @     0x7f6e34aa8c50  caffe::TiledPredict<>()
    @           0x408e6f  tiled_predict()
    @           0x4076a0  main
    @     0x7f6e329b7830  __libc_start_main
    @           0x407ef9  _start
    @              (nil)  (unknown)

what is wrong? Can you help me ?

**Comment by ThorstenFalk** [comment]
It looks like you exceeded the available RAM of your instance
