### ISSUE TITLE
How to train caffe_unet directly on custom data set?

### ISSUE THREAD

**Issue by lixiangchun** [lmb-freiburg/Unet-Segmentation#39]
I want to train caffe unet on custom data set without using ImageJ. Any tutorial related to this topic is highly appreciated.

**Comment by ThorstenFalk** [comment]
If you don't want to use ImageJ, please check our previous [MICCAI paper](https://link.springer.com/chapter/10.1007%2F978-3-319-24574-4_28)  with associated resources
