### ISSUE TITLE
Macro Execution ignores model

### ISSUE THREAD

**Issue by BolekZapiec** [lmb-freiburg/Unet-Segmentation#43]
Hi, 
I'm not sure when this change took place, but with the current version of the plugin, it appears to ignore the parameters of executing the job from macro and just uses the model/weights selected in the dialog box. Even if e.g. the last GUI job was a detection job, if you execute a segmentation job with specifying the parameters - it still executes the job with the settings from the last GUI job. 

I even tried re-recording the commands in case syntax changed but the behavior remains. 

To elaborate: 
I have a ModelA and WeightsA selected in GUI as the last job I did (doesn't matter if it was segmentation or detection)
I execute a macro asking for segmentation with ModelB and WeightsB 
Result: it executes segmentation with ModelA and WeightsA

This is on Ubuntu Fiji 1.52o running the "latest" Unet according to the update site - I haven't yet tested if it's the same on windows.

**Comment by Jay-Beeb** [comment]
I have the same problem on Windows. The call function seems to not use selected model and weight files but the ones that were last used via the Job Manager

**Comment by ThorstenFalk** [comment]
The latest revision on the Fiji Update site should fix the issue. The problem was, that even in non-interactive mode the parameters dialog was setup and populated with values from ij.Prefs.
