### ISSUE TITLE
"cat: tmp" No such file or directory" Error

### ISSUE THREAD

**Issue by collegeblock** [lmb-freiburg/Unet-Segmentation#45]
Hi everyone,

I'm currently trying to install and use Unet for some cell quantification. I decided to go with AWS option, however I'm having some troubles passing by this step:
" echo "export PATH=$PATH:/home/ubuntu/caffe_unet_package_16.04_gpu_no_cuDNN/bin" | cat - tmp > ~/.bashrc" 
I get an error saying: "cat: tmp" No such file or directory"

Could you please help with this?
Thank you in advance.
Best.

**Comment by ThorstenFalk** [comment]
Agreed, this is a documentation error, strange that nobody stumbled over it before.

Please use the following commands (updated on the website):

```
cd ~
wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
sudo apt-get update
sudo apt-get install -y cuda-8.0 unzip
sudo apt-get clean
wget https://lmb.informatik.uni-freiburg.de/lmbsoft/unet/caffe_unet_package_16.04_gpu_no_cuDNN.zip
unzip caffe_unet_package_16.04_gpu_no_cuDNN.zip
echo "export PATH=$PATH:/home/ubuntu/caffe_unet_package_16.04_gpu_no_cuDNN/bin" | cat - ~/.bashrc > tmp
echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/ubuntu/caffe_unet_package_16.04_gpu_no_cuDNN/lib:/home/ubuntu/caffe_unet_package_16.04_gpu_no_cuDNN/extlib:/usr/local/cuda-8.0/lib64" | cat - tmp > ~/.bashrc
```

**Comment by collegeblock** [comment]
Perfect! Thank you very much!
Have a nice day.
