### ISSUE TITLE
caffe_unet was not found

### ISSUE THREAD

**Issue by GloriaZLQ** [lmb-freiburg/Unet-Segmentation#46]
I setup on own server (using pre-built binaries)
when I test: start a new shell and execute "caffe",it's fine;
but when I execute"ssh localhost caffe",there's a error:

> "zsh:1: command not found: caffe"

and when I use ImageJ according to your teaching video  setp by step,something is wrong:

> "caffe_unet was not found".

![B47A67E92D224B3B82D6318A55FDA3D3](https://user-images.githubusercontent.com/38201071/61268368-cb275e80-a7cd-11e9-9b2f-ffc594867bad.jpg)

![85034084D4444BDF9304D0AD0F63F4DC](https://user-images.githubusercontent.com/38201071/61268477-25282400-a7ce-11e9-92a9-74cfc8d9a960.jpg)

**Comment by ThorstenFalk** [comment]
You are using zsh? Then changes in .bashrc won't take effect, since they are only executed when starting bash shells. Add all required paths to .profile directly, if this does not help, consult your user's manual for environment setup in zsh.

**Comment by GloriaZLQ** [comment]
> You are using zsh? Then changes in .bashrc won't take effect, since they are only executed when starting bash shells. Add all required paths to .profile directly, if this does not help, consult your user's manual for environment setup in zsh.

Thanks.The reason for the problem what that $PATH wasn't set in non-interactive sessions 
I solved it：

> ln -s /etc/zsh/zshenv zshenv
and added  the required paths in .zshenv
