### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by JahnJ** [lmb-freiburg/Unet-Segmentation#48]
I recently tried to finetune a model, but run into following error, when starting the finetune process:
> Exception in thread "Thread-10" java.lang.NoSuchMethodError: de.unifreiburg.unet.ProgressMonitor.taskProgressMax()F
	at de.unifreiburg.unet.FinetuneWithRoisJob.run(FinetuneWithRoisJob.java:291)

I trief with a fresh Fiji-Download from http://fiji.sc ; deleted the IJ_Prefs.txt file; and a clean install of the U-Net Plugin via the "Manage update sites". Tried it on 2 different machines (Win 8.1/10), but still the same error. Backend server is running Ubuntu 16.04 LTS with the "caffe_unet_package_16.04_gpu_cuDNN.zip" prebuild binary. Segmentation workes fine.

Also when pressing the "from Image" button for element size a similar error occurs:

> Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: de.unifreiburg.unet.Tools.getElementSizeUmFromCalibration(Lij/measure/Calibration;I)[D
	at de.unifreiburg.unet.FinetuneWithRoisJob$1.actionPerformed(FinetuneWithRoisJob.java:166)

Any idea how to fix it?
Thank you very much!

![grafik](https://user-images.githubusercontent.com/53092026/61548985-3d5aa600-aa4f-11e9-8d56-51a9298de80b.png)

**Comment by JahnJ** [comment]
[Labeled_image.zip](https://github.com/lmb-freiburg/Unet-Segmentation/files/3411873/Labeled_image.zip)

**Comment by ThorstenFalk** [comment]
Thanks for pointing this out. A seemingly unrelated problem already bugged me for a while, but now after seeing your error message I could finally localize and fix it.

**Comment by JahnJ** [comment]
Thank you very much for this rapid fix.
Update the plugin and it works fine!
