### ISSUE TITLE
hungarian_algorithm.cpp:84] Check failed: value >= 0 (-nan vs. 0) All matrix elements have to be non-negative.

### ISSUE THREAD

**Issue by pilletb** [lmb-freiburg/Unet-Segmentation#49]
Hi! I'm trying to train a 3d model from scratch using a 332 resolution without normalization. My system is Ubuntu 18.04 with CuDNN 7.6 and Cuda 10.0.
For the hardware part:
2x GTX970 4gb (I used only the GPU1)
I7 4790K
16gb of RAM
I get the error below after a few thousand iterations if I have validation images (in local). the time before error seems to link to the size of the validation images and frequency of the validation steps but not completely sure... I tried to do it remotely with 3 small images to see if it would be better but if I put 1 image in the validation it gives me the same message directly at the starts.

Here are the message and log from a remote test

![Capture](https://user-images.githubusercontent.com/53425146/62031811-809fdc00-b1e8-11e9-97c5-a425d9a97af1.PNG)
[Log.txt](https://github.com/lmb-freiburg/Unet-Segmentation/files/3441002/Log.txt)

I0728 11:44:18.950510  4121 softmax_loss_layer.cu:93] SoftmaxWithLoss warning: sum of pixel wise loss weights is zero!
I0728 11:44:18.950646  4121 iou_layer.cu:89]     IoU - Per class intersection: 0 
I0728 11:44:18.950652  4121 iou_layer.cu:91]     IoU - Per class union: 0 
I0728 11:44:18.951164  4121 f1_layer.cpp:387]     F1_detection - Per class true positive count: 0 
I0728 11:44:18.951170  4121 f1_layer.cpp:389]     F1_detection - Per class prediction count: 0 
I0728 11:44:18.951174  4121 f1_layer.cpp:391]     F1_detection - Per class object count: 0 
I0728 11:44:18.951588  4121 f1_layer.cpp:387]     F1_segmentation - Per class true positive count: 0 
I0728 11:44:18.951593  4121 f1_layer.cpp:389]     F1_segmentation - Per class prediction count: 0 
I0728 11:44:18.951596  4121 f1_layer.cpp:391]     F1_segmentation - Per class object count: 0 
I0728 11:44:19.146605  4121 iou_layer.cu:89]     IoU - Per class intersection: 5 
I0728 11:44:19.146618  4121 iou_layer.cu:91]     IoU - Per class union: 3586 
F0728 11:44:19.147724  4121 hungarian_algorithm.cpp:84] Check failed: value >= 0 (-nan vs. 0) All matrix elements have to be non-negative.
*** Check failure stack trace: ***
    @     0x7f06c6bd30cd  google::LogMessage::Fail()
    @     0x7f06c6bd4f33  google::LogMessage::SendToLog()
    @     0x7f06c6bd2c28  google::LogMessage::Flush()
    @     0x7f06c6bd5999  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f06c7334f60  HungarianAlgorithm::assignmentoptimal()
    @     0x7f06c733544a  HungarianAlgorithm::Solve()
    @     0x7f06c722fa27  caffe::F1Layer<>::Forward_cpu()
    @     0x7f06c72e4ee7  caffe::Net<>::ForwardFromTo()
    @     0x7f06c72e51f7  caffe::Net<>::Forward()
    @     0x7f06c7302290  caffe::Solver<>::Test()
    @     0x7f06c7302a07  caffe::Solver<>::TestAll()
    @     0x7f06c7304c2b  caffe::Solver<>::Step()
    @     0x7f06c7304e2d  caffe::Solver<>::Solve()
    @     0x556a11596384  train()
    @     0x556a1159205a  main
    @     0x7f06c595eb97  __libc_start_main
    @     0x556a11592a5a  _start

In the end, I can work with it locally but I always need to do only 3000-5000 iterations each session which is not ideal. I hope that I just configured something wrong and that there is a simple fix because the first results are encouraging. Thank you for this great work!

**Comment by ThorstenFalk** [comment]
Errors that only occur infrequently after a while are quite hard to debug. I first need to find a test case. From the code I don't see how -nan values creep into the cost matrix.

**Comment by ThorstenFalk** [comment]
It would help me a lot if you could provide the one validation image that directly provokes the error?

**Comment by pilletb** [comment]
In local it happens infrequently but consistently. If a start from a certain model with the same set of images it will always crash at the same iteration.
And via SSH remotely it happens instantly every time if a validation image is set. I will test if I use SSH localhost address to see if it create the same problem.

Here are the 3 images used, image 1 and 2 for training and image 3 for validation

[test_images.zip](https://github.com/lmb-freiburg/Unet-Segmentation/files/3446651/test_images.zip)

**Comment by ThorstenFalk** [comment]
I just started two trainings one with element size of the microspore model [1] and one with element size of your images [2]. Both trainings are on a remote host, since I only have a poor GPU in my machine.
With model [1]: IoU > 0 after iteration 100 with lr 1e-4, now at 0.4 after 250 iterations from scratch.

**Comment by ThorstenFalk** [comment]
2000iters, no crash
[1]: IoU 0.65
[2]: IoU 0.8

**Comment by pilletb** [comment]
Thank you for testing the images. I guess the problem comes from my hardware or configuration. I will do some tests see if I can narrow down the possible explanations

**Comment by ThorstenFalk** [comment]
I'll leave it running, but usually with stabilization of the model fewer problematic corner-cases occur. Hardware and configuration are not completely impossible but I'd say unlikely, maybe a change in cuDNN or cuda, but usualyy these libraries are well tested...

**Comment by pilletb** [comment]
After few test I noticed that remote was not the issue but the normalization was. With this model def I get the error all the time (using the same images).
[u-net-3D-332-64_noNorm.modeldef.zip](https://github.com/lmb-freiburg/Unet-Segmentation/files/3449861/u-net-3D-332-64_noNorm.modeldef.zip)
The reason why I wanted to try without normalization is that these small images are part of bigger images (2048x2048x51) and my model work well on the small images but when use on the full image some of the weaker nucleus were not detected or poorly segmented because the normalization is different. There often is few weird cells or debris that has a value between 50000 to 60000 therefore completely changing the max.
The problem also happened with normalization but not frequently. I will share the weights, model def and parameters when that will happen again that you can try reproduce the crash.

**Comment by ThorstenFalk** [comment]
Ah, you turned automatic normalization off. Did you normalize the images manually then? One requirement for using the value augmentation layer is that the data range is in [0,1], values out of this range are clipped, i.e. if you pass the raw intensities, after value augmentation you will end up with an entirely white image and the network will perform extremely poor.

If you have bright debris as you describe I would recommend to normalize the whole stacks with a robust percentile filter, e.g. if less than 1% of the pixels are outliers due to debris pick the 1%-99% histogram percentile and map it to the [0,1] range and then select "No normalization". Out-of-range pixels will be clipped by the value augmentation layer, so that the network can easily learn that saturated or zero pixels should be ignored.

Generally I would recommend to use the full stacks for training to minimize artifacts due to boundary treatment (I recommend to still validate on small crops to reduce the validation overhead).

**Comment by pilletb** [comment]
No, I didn't manually normalize them. Then I will have a look at the full stack to see what would be the best normalization strategy. Thank you and I will post here if this error happened again with properly prepared data.
