### ISSUE TITLE
"caffe_unet was not found" When accessing from Windows

### ISSUE THREAD

**Issue by Vector2020** [lmb-freiburg/Unet-Segmentation#52]
Hi,
I have set up caffe and everything else in Ubuntu 18 with Cuda 10.0 and cudnn. Actually I tested the unet segmentation plugin in the Ubuntu and it worked (I could segment an image with the unet plugin)!
 Now, I am trying to run the plugin in a windows 10 laptop. But after I enter the host name, user/password and press OK, I get the error : 
"caffe_unet was not found.
Please specify your caffe_unet binary". 
Does anybody know how to solve this issue?
Thanks!
PS. I have already added the variables to the  .bashrc and .profile. Also, I have checked the   caffe_unet in the the terminal of Bitvise SSH client and it recognized caffe_unet.

**Comment by ThorstenFalk** [comment]
If it works using your SSH client, it should also work using the plugin. It does nothing more than establishing an SSH connection end executing caffe_unet. Can you provide the corresponding output log? I assume it is boring and only contains something like U-Net segmentation plugin started and checking for caffe_unet. But if there is more it might be of interest.
