### ISSUE TITLE
Macro commands of the Fiji plugin U-net

### ISSUE THREAD

**Issue by ech3000** [lmb-freiburg/Unet-Segmentation#53]
Does anybody know what the commands (macro language, java, or whatever) are for interacting with the U-net plugin? 
Specifically to run a segmentation job. For example, I'd like to write a macro to input several images (a stack), do some post-processing in fiji, and save their output. All I need (I think) is the command to run a segmentation job. (I tried using the macro recorder, it does not record the interaction with the U-net plugin.)
Thanks in advance.

**Comment by ThorstenFalk** [comment]
The easiest way of getting the command is to record a macro while executing a Segmentation job. After the job finishes the command you are searching for will be recorded.

Something similar to
call('de.unifreiburg.unet.SegmentationJob.processHyperStack', 'modelFilename=<path to 2d_cell_net_v0.modeldef.h5>,Memory (MB):=6000,weightsFilename=2d_cell_net_v0.caffemodel.h5,gpuId=GPU0,useRemoteHost=true,hostname=<hostname>,port=22,username=<username>,RSA key=<path to RSA key>,processFolder=,average=none,keepOriginal=true,outputScores=true,outputSoftmaxScores=false');
should be recorded.
