### ISSUE TITLE
Cannot select model folder

### ISSUE THREAD

**Issue by freudwasright** [lmb-freiburg/Unet-Segmentation#61]
Hi,
When I want to use for example segmentation within the u-net plugin,  and select the caffemodels folder, the selected folder won't be appended. It's like it doesn't find the path or something. The other folder appending features are working correctly, there is a problem with only this one. And if I dont select a model folder it responds with (as can be seen on the image) "no file model selected".
I hope it was clear enough, if not and you have further questions please don't hesitate.
Thanks in advance.

![u-net bug](https://user-images.githubusercontent.com/57996039/77256429-78f8e000-6c6e-11ea-8f2b-634d26bf3e95.JPG)
![u-net_bug2](https://user-images.githubusercontent.com/57996039/77256430-79917680-6c6e-11ea-8ce2-a97690dc07fe.JPG)

**Comment by ThorstenFalk** [comment]
The model folder must contain .modeldef.h5 files. The plugin will check those paths for a valid u-net model id and then append their name string to the combobox. So either your folder did not contain any modeldef.h5 file or the contained files are corrupt and do not contain required model parameters, starting with .unet-ident attribute over unet_param/name, and architecture details.

**Comment by freudwasright** [comment]
Alright, if by any chance they would be corrupted somehow, could you please give me a link, where I can get the correct files?
The caffe model files contained the following by the way.
![image](https://user-images.githubusercontent.com/57996039/77303753-c3707000-6cf3-11ea-9104-b70cc39eb576.png)

**Comment by ThorstenFalk** [comment]
If you use our shipped models, everything is contained. There is no other downlaod location and I heard from nobody else that they did not work as expected. The only option I see is that you accidentally selected the wrong folder.

**Comment by freudwasright** [comment]
Well I'm pretty sure that I've selected the right folder, I recorded a small video about the process if that might help, but I can't upload mp4 files due to it being not supported by github. Any suggestion for the second problem's workaround maybe, how I can check into it ,what I can do about it?

**Comment by freudwasright** [comment]
Well thanks a lot :) .
