### ISSUE TITLE
Bash: caffe: command not found

### ISSUE THREAD

**Issue by freudwasright** [lmb-freiburg/Unet-Segmentation#65]
Hi, I did everything accordingly to the step by step guide, I set the environment for caffe and the caffe usage message appears. But when I try to  check wether i can connect via ssh "ssh localhost caffe", after login it says bash: caffe: command not found. 
Any idea how to resolve this issue? Thanks in advance

**Comment by ThorstenFalk** [comment]
You are running Ubuntu and edited .profile to setup the environment? If you edited .bashrc you have to additionally source .bashrc in .profile for ssh logins.

**Comment by freudwasright** [comment]
Thanks its working! Also could you please tell me, when using detection, how to show only points with over 0.75 confidence for example?

**Comment by freudwasright** [comment]
Anyway I found an exhausting way to do it, so this thread can be closed, but if you have a suggestion I'd appreciate it. Thanks a lot anyway!

**Comment by ThorstenFalk** [comment]
Confidence-levels are beyond the capabilities of standard convolutional neural networks. If treating the output scores (after soft-max) as pseudo-probabilities, confidence levels are massively over-confident even if they are completely wrong. There are different approaches to obtain uncertainties which usually involve sampling by multiple network runs with different drop-outs during forward pass computation or multi-headed outputs to compute pseudo-probabilities.
