### ISSUE TITLE
null pointer exception in checkParameters() of SegmentationJob

### ISSUE THREAD

**Issue by ThorstenFalk** [lmb-freiburg/Unet-Segmentation#9]
Issue detail: When runs segmentation job using BF example dataset and pretrained model provided by the paper, exception occurs:

Exception in thread "Thread-5" java.lang.NullPointerException
     at de.unifreiburg.unet.SegmentationJob.checkParameters(SegmentationJob.java:390)
     at de.unifreiburg.unet.SegmentationJob.getParameters(SegmentationJob.java:438)
     at de.unifreiburg.unet.SegmentationJob.run(SegmentationJob.java:661)

log file indicates:

$ /home/daveb/unet-seg/bin/caffe_unet
$ /home/daveb/unet-seg/bin/caffe_unet
$ caffe_unet check_model_and_weights_h5 -model /home/daveb/Downloads/caffemodels/2d_cell_net_v0.modeldef.h5 -weights /home/daveb/Downloads/2d_cell_net_v0.caffemodel.h5 -n_channels 1 -gpu 0

Installation and OS details:

Build from source (using instructions from project website);

No backend used (running caffe_unet in terminal correctly shows usage information)

Ubuntu 18.04 LTS, CUDA 9.0 CuDNN 7

**Comment by ThorstenFalk** [comment]
The checkParameters() function grew too big. Refacturing required to make it more maintainable. It looks like the ProcessResult, that is initialized with null is never set in the function in this case.

**Comment by ThorstenFalk** [comment]
checkParameters() function simplified. Exceptions and failing processes now immediately make the check fail which should as a side-effect fix this bug.

**Comment by yinawang28** [comment]
Hi Thorsten, do you mind share a description of the dependencies and how to build it from source? Thanks a lot!

**Comment by ThorstenFalk** [comment]
README.md has been extended accordingly.
